apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-api-config
  namespace: iris-api
data:
  API_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  MODEL_PATH: "/app/artifacts/model.joblib"
  DATA_PATH: "/app/data/iris.csv"
  MLFLOW_TRACKING_URI: "http://localhost:5000"
  MLFLOW_BACKEND_STORE_URI: "sqlite:////app/mlruns/mlflow.db"
  MLFLOW_ARTIFACT_ROOT: "/app/mlruns"