apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iris-api-ingress
  namespace: iris-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: iris-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iris-api-service
            port:
              number: 80